name: Code checks
on: 
  pull_request:
    types:
      - synchronize
      - labeled
  push:
    branches: [develop, master]

jobs:
  code:
    if: ${{ (github.event.push != null) || contains(github.event.pull_request.labels.*.name, 'Code') }}
    runs-on: ubuntu-latest
    steps:
      - name: Code checks placeholder
        run: echo "TODO - more code checks to go here (static, unit-tests)"