name: Documentation
on: 
  pull_request:
    types:
      - synchronize
      - labeled
  push:
    branches: [develop, master]

jobs:
  code:
    if: (github.event_name == 'push') || contains(github.event.pull_request.labels.*.name, 'Docs')
    runs-on: ubuntu-latest
    steps:
      - name: Docs build placeholder
        run: echo "TODO - build and validate docs, create unpackaged asset for easy inspection"